openapi: 3.0.0
info:
  title: 'API Testing With Swagger'
  description: 'API Testing With Swagger'
  termsOfService: ''
  contact:
    email: dominhthong99@gmail.com
  version: 1.0.0
servers:
  -
    url: /ict_hub
paths:
  '/?controller=articles':
    get:
      summary: 'Return all article'
      description: 'Return all article'
      operationId: 'ArticlesController::index'
      responses:
        '200':
          description: Success
        '404':
          description: 'Not found'
  '/?controller=semesters':
    get:
      summary: 'Return all semester'
      description: 'Return all semester'
      operationId: 'SemestersController::index'
      responses:
        '200':
          description: Success
        '404':
          description: 'Not found'
